name: "test-local"
on:
  workflow_dispatch:

jobs:
  tests:
    name: Test action from local source
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        npm ci

    - name: Build package
      run: |
        npm run build

    - name: Run action from local source
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
