name: "tests"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        npm ci

    - name: Lint
      run: |
        npm run lint

    - name: Run tests
      run: |
        npm test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

    - name: Try building
      run: |
        npm run build

  notify:
    name: Notify failed build
    needs: tests
    if: failure() && github.event.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - uses: jayqi/failed-build-issue-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
