name: zizmor

on:
  push:
    branches: [main]
    paths: [".github/**"]
  pull_request:
    paths: [".github/**"]
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    name: Run Zizmor audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          advanced-security: false

  notify:
    name: Notify failed build
    needs: [zizmor]
    if: failure() && (github.event_name == 'push' || github.event_name == 'schedule')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: jayqi/failed-build-issue-action@1a893bbf43ef1c2a8705e2b115cd4f0fe3c5649b # v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
